spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:mysql://localhost:3306/cufaConecta
    username: admCufa
    password: cufaConecta@2025
  jackson:
    default-property-inclusion: non_null
#  flyway:
#    enabled: true
#    locations:
#      classpath: db/migration

jwt:
  validity: 86400
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YX]
