server:
  port: 8080
  address: 0.0.0.0

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: localhost
    port: 5672
    username: myuser
    password: secret

jwt:
  validity: 86400
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YX]

