spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  datasource:
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PASS}
  jackson:
    default-property-inclusion: non_null

jwt:
  validity: 3600000
  secret: RXhpc3RlIHVtYSB0ZW9yaWEgcXVlIGRpeiBxdWUsIHNlIHVtIGRpYSBhbGd16W0gZGVzY29icmlyIGV4YX]
#
#  flyway:
#    enabled: true
#    locations:
#      classpath: db/migration
#      default-schema: cufa
