spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-autcufaConectao: none
  datasource:
    url: jdbc:mysql://localhost:3306/cufaConecta
    username: admCufa
    password: cufaConecta@2025
  jackson:
    default-property-inclusion: non_null
#  flyway:
#    enabled: true
#    locations:
#      classpath: db/migration
#      default-schema: cufa
